(ns lpddr_mobile.actor
  "lpddr_mobile clean-room actor — Clojure over the kotoba Datom log (EAVT, Datomic-isomorphic,
  ADR-2605262130 + ADR-2605312345). LPDDR mobile / low-power DRAM design.

  Generated by 70-tools/scaffold_wave11_clj_datomic.py — replaces the Python main.py.
  CRUD + validation over a DI `DatomPort` seam (no external managed DB; the production
  adapter is kotoba-kqe, the test/browser adapter is `in-memory-datom`). No proprietary code."
  (:require [clojure.string :as str]))

;; ── Datomic-style schema (install via -transact) ──────────────────────────
(def schema
  "Attribute installs for this actor's entities (Datomic schema shape)."
  [;; LpddrDevice
   {:db/ident :lpddr_mobile.LpddrDevice/id :db/valueType :db.type/string :db/cardinality :db.cardinality/one :db/unique :db.unique/identity}
   {:db/ident :lpddr_mobile.LpddrDevice/partNumber :db/valueType :db.type/string :db/cardinality :db.cardinality/one}
   {:db/ident :lpddr_mobile.LpddrDevice/generation :db/valueType :db.type/string :db/cardinality :db.cardinality/one}
   {:db/ident :lpddr_mobile.LpddrDevice/densityGb :db/valueType :db.type/long :db/cardinality :db.cardinality/one}
   {:db/ident :lpddr_mobile.LpddrDevice/dataRateMtps :db/valueType :db.type/long :db/cardinality :db.cardinality/one}
   {:db/ident :lpddr_mobile.LpddrDevice/createdAt :db/valueType :db.type/instant :db/cardinality :db.cardinality/one}
   {:db/ident :lpddr_mobile.LpddrDevice/updatedAt :db/valueType :db.type/instant :db/cardinality :db.cardinality/one}
   ;; Channel
   {:db/ident :lpddr_mobile.Channel/id :db/valueType :db.type/string :db/cardinality :db.cardinality/one :db/unique :db.unique/identity}
   {:db/ident :lpddr_mobile.Channel/deviceId :db/valueType :db.type/string :db/cardinality :db.cardinality/one}
   {:db/ident :lpddr_mobile.Channel/width :db/valueType :db.type/long :db/cardinality :db.cardinality/one}
   {:db/ident :lpddr_mobile.Channel/index :db/valueType :db.type/long :db/cardinality :db.cardinality/one}
   {:db/ident :lpddr_mobile.Channel/dataRateMtps :db/valueType :db.type/long :db/cardinality :db.cardinality/one}
   {:db/ident :lpddr_mobile.Channel/createdAt :db/valueType :db.type/instant :db/cardinality :db.cardinality/one}
   {:db/ident :lpddr_mobile.Channel/updatedAt :db/valueType :db.type/instant :db/cardinality :db.cardinality/one}
   ;; PowerMode
   {:db/ident :lpddr_mobile.PowerMode/id :db/valueType :db.type/string :db/cardinality :db.cardinality/one :db/unique :db.unique/identity}
   {:db/ident :lpddr_mobile.PowerMode/deviceId :db/valueType :db.type/string :db/cardinality :db.cardinality/one}
   {:db/ident :lpddr_mobile.PowerMode/name :db/valueType :db.type/string :db/cardinality :db.cardinality/one}
   {:db/ident :lpddr_mobile.PowerMode/currentMa :db/valueType :db.type/double :db/cardinality :db.cardinality/one}
   {:db/ident :lpddr_mobile.PowerMode/voltageV :db/valueType :db.type/double :db/cardinality :db.cardinality/one}
   {:db/ident :lpddr_mobile.PowerMode/createdAt :db/valueType :db.type/instant :db/cardinality :db.cardinality/one}
   {:db/ident :lpddr_mobile.PowerMode/updatedAt :db/valueType :db.type/instant :db/cardinality :db.cardinality/one}
   ;; TimingProfile
   {:db/ident :lpddr_mobile.TimingProfile/id :db/valueType :db.type/string :db/cardinality :db.cardinality/one :db/unique :db.unique/identity}
   {:db/ident :lpddr_mobile.TimingProfile/deviceId :db/valueType :db.type/string :db/cardinality :db.cardinality/one}
   {:db/ident :lpddr_mobile.TimingProfile/casLatency :db/valueType :db.type/long :db/cardinality :db.cardinality/one}
   {:db/ident :lpddr_mobile.TimingProfile/tRCD :db/valueType :db.type/long :db/cardinality :db.cardinality/one}
   {:db/ident :lpddr_mobile.TimingProfile/tRP :db/valueType :db.type/long :db/cardinality :db.cardinality/one}
   {:db/ident :lpddr_mobile.TimingProfile/createdAt :db/valueType :db.type/instant :db/cardinality :db.cardinality/one}
   {:db/ident :lpddr_mobile.TimingProfile/updatedAt :db/valueType :db.type/instant :db/cardinality :db.cardinality/one}
   ;; SpeedBin
   {:db/ident :lpddr_mobile.SpeedBin/id :db/valueType :db.type/string :db/cardinality :db.cardinality/one :db/unique :db.unique/identity}
   {:db/ident :lpddr_mobile.SpeedBin/deviceId :db/valueType :db.type/string :db/cardinality :db.cardinality/one}
   {:db/ident :lpddr_mobile.SpeedBin/grade :db/valueType :db.type/string :db/cardinality :db.cardinality/one}
   {:db/ident :lpddr_mobile.SpeedBin/voltageV :db/valueType :db.type/double :db/cardinality :db.cardinality/one}
   {:db/ident :lpddr_mobile.SpeedBin/dataRateMtps :db/valueType :db.type/long :db/cardinality :db.cardinality/one}
   {:db/ident :lpddr_mobile.SpeedBin/createdAt :db/valueType :db.type/instant :db/cardinality :db.cardinality/one}
   {:db/ident :lpddr_mobile.SpeedBin/updatedAt :db/valueType :db.type/instant :db/cardinality :db.cardinality/one}
   ;; JedecSpec
   {:db/ident :lpddr_mobile.JedecSpec/id :db/valueType :db.type/string :db/cardinality :db.cardinality/one :db/unique :db.unique/identity}
   {:db/ident :lpddr_mobile.JedecSpec/deviceId :db/valueType :db.type/string :db/cardinality :db.cardinality/one}
   {:db/ident :lpddr_mobile.JedecSpec/standard :db/valueType :db.type/string :db/cardinality :db.cardinality/one}
   {:db/ident :lpddr_mobile.JedecSpec/revision :db/valueType :db.type/string :db/cardinality :db.cardinality/one}
   {:db/ident :lpddr_mobile.JedecSpec/compliant :db/valueType :db.type/boolean :db/cardinality :db.cardinality/one}
   {:db/ident :lpddr_mobile.JedecSpec/createdAt :db/valueType :db.type/instant :db/cardinality :db.cardinality/one}
   {:db/ident :lpddr_mobile.JedecSpec/updatedAt :db/valueType :db.type/instant :db/cardinality :db.cardinality/one}])

(def entities #{"LpddrDevice" "Channel" "PowerMode" "TimingProfile" "SpeedBin" "JedecSpec"})

;; ── DatomPort — the DI seam to the kotoba Datom log ───────────────────────
(defprotocol DatomPort
  (-transact [this tx-data]
    "Append Datomic-shaped tx-data: entity maps {:db/id … attr v}, [:db/add e a v],
     [:db/retract e a v], [:db/retractEntity e].")
  (-pull [this eid]
    "Return the entity map for eid (incl. :db/id), or nil.")
  (-find-by-attr [this attr]
    "AEVT scan: the eids of every entity carrying attr."))

;; loud-failing default — a forgotten injection must never silently no-op
(defn unwired-datom []
  (reify DatomPort
    (-transact [_ _] (throw (ex-info "lpddr_mobile: DatomPort not wired — inject kotoba-kqe or in-memory-datom" {:unwired true})))
    (-pull [_ _] (throw (ex-info "lpddr_mobile: DatomPort not wired" {:unwired true})))
    (-find-by-attr [_ _] (throw (ex-info "lpddr_mobile: DatomPort not wired" {:unwired true})))))

;; in-memory fake — interprets the Datomic tx-data subset over {eid {attr v}}
(defn in-memory-datom []
  (let [store (atom {})]
    (reify DatomPort
      (-transact [_ tx-data]
        (doseq [op tx-data]
          (cond
            (map? op) (swap! store update (:db/id op) merge (dissoc op :db/id))
            (and (vector? op) (= :db/add (first op)))
            (let [[_ e a v] op] (swap! store assoc-in [e a] v))
            (and (vector? op) (= :db/retract (first op)))
            (let [[_ e a] op] (swap! store update e dissoc a))
            (and (vector? op) (= :db/retractEntity (first op)))
            (let [[_ e] op] (swap! store dissoc e))))
        {:db-after @store})
      (-pull [_ eid] (when-let [m (get @store eid)] (assoc m :db/id eid)))
      (-find-by-attr [_ attr] (vec (for [[eid m] @store :when (contains? m attr)] eid))))))

;; ── coercion (portable) ───────────────────────────────────────────────────
(defn- as-long [v]
  (cond (number? v) #?(:clj (long v) :cljs v)
        (string? v) (try #?(:clj (Long/parseLong (str/trim v))
                            :cljs (let [n (js/parseInt v 10)] (if (js/isNaN n) 0 n)))
                         (catch #?(:clj Exception :cljs :default) _ 0))
        :else 0))

(defn- as-double [v]
  (cond (number? v) #?(:clj (double v) :cljs v)
        (string? v) (try #?(:clj (Double/parseDouble (str/trim v))
                            :cljs (let [n (js/parseFloat v)] (if (js/isNaN n) 0.0 n)))
                         (catch #?(:clj Exception :cljs :default) _ 0.0))
        :else 0.0))

(defn- as-bool [v]
  (boolean (#{"1" "true" "yes" "on" true} (if (string? v) (str/lower-case v) v))))

(defn- now []
  #?(:clj (str (java.time.Instant/now)) :cljs (.toISOString (js/Date.))))

(defn- new-id [prefix]
  (str prefix "_" (subs (str/replace (str (random-uuid)) "-" "") 0 16)))

(defn- require-fields [data fields]
  (let [missing (remove (fn [k] (some? (get data (keyword k)))) fields)]
    (when (seq missing)
      (throw (ex-info (str "Missing required fields: " (str/join ", " missing))
                      {:type :invalid-request :missing (vec missing)})))))

;; ── list surface: filtering + cursor pagination (L4 parity) ───────────────
(def ^:const default-limit 20)
(def ^:const max-limit 100)

(defn- index-of [v x]
  (loop [i 0] (cond (>= i (count v)) -1 (= (nth v i) x) i :else (recur (inc i)))))

(defn- apply-filters
  "Keep rows matching every {attr v} in flt (string-compared), attr restricted to allowed."
  [rows flt allowed]
  (let [allowed (set allowed)]
    (reduce (fn [rs [a v]]
              (if (and (contains? allowed a) (some? v))
                (filterv (fn [r] (= (str (get r a)) (str v))) rs)
                rs))
            (vec rows) (or flt {}))))

(defn- paginate
  "Cursor pagination over rows → {:object :data :has-more :count :total}.
   opts {:limit N :starting-after <db/id>}."
  [rows opts]
  (let [limit (min (max (or (:limit opts) default-limit) 1) max-limit)
        start (:starting-after opts)
        rows  (vec rows)
        rows  (if start
                (let [idx (index-of (mapv :db/id rows) start)]
                  (if (neg? idx) rows (subvec rows (inc idx))))
                rows)
        page  (vec (take limit rows))]
    {:object "list" :data page :has-more (> (count rows) limit)
     :count (count page) :total (count rows)}))

;; ── LpddrDevice ────────────────────────────────────────────────────────────────
(defn create-lpddr-device
  "Create a LpddrDevice."
  [port data]
  (require-fields data ["partNumber" "generation"])
  (let [id (new-id "lpd_lpd")
        e {:db/id id
           :lpddr_mobile.LpddrDevice/id id
           :lpddr_mobile.LpddrDevice/partNumber (get data :partNumber)
           :lpddr_mobile.LpddrDevice/generation (get data :generation)
           :lpddr_mobile.LpddrDevice/densityGb (as-long (get data :densityGb))
           :lpddr_mobile.LpddrDevice/dataRateMtps (as-long (get data :dataRateMtps))
           :lpddr_mobile.LpddrDevice/createdAt (now)
           :lpddr_mobile.LpddrDevice/updatedAt (now)}]
    (-transact port [e])
    e))

(defn list-lpddr-devices
  "List LpddrDevice with optional filtering + cursor pagination → L4 list map.
   opts: {:filter {<attr-kw> v} :limit N :starting-after <db/id>}."
  ([port] (list-lpddr-devices port {}))
  ([port opts]
   (let [rows (mapv (fn [e] (-pull port e)) (-find-by-attr port :lpddr_mobile.LpddrDevice/id))
         rows (apply-filters rows (:filter opts) [:lpddr_mobile.LpddrDevice/partNumber :lpddr_mobile.LpddrDevice/generation :lpddr_mobile.LpddrDevice/densityGb :lpddr_mobile.LpddrDevice/dataRateMtps])]
     (paginate rows opts))))

(defn get-lpddr-device
  "Retrieve a LpddrDevice by id; opts {:expand #{:field}} inlines referenced entities. nil if absent."
  ([port id] (get-lpddr-device port id nil))
  ([port id opts]
   (when-let [rec (-pull port id)]
     (let [want (:expand opts)]
       (cond-> rec)))))

(defn update-lpddr-device
  "Update a LpddrDevice; returns the new entity map, or nil if absent."
  [port id data]
  (when (-pull port id)
    (let [sets (-> []
                   (cond-> (contains? data :partNumber) (conj [:db/add id :lpddr_mobile.LpddrDevice/partNumber (get data :partNumber)]))
                   (cond-> (contains? data :generation) (conj [:db/add id :lpddr_mobile.LpddrDevice/generation (get data :generation)]))
                   (cond-> (contains? data :densityGb) (conj [:db/add id :lpddr_mobile.LpddrDevice/densityGb (as-long (get data :densityGb))]))
                   (cond-> (contains? data :dataRateMtps) (conj [:db/add id :lpddr_mobile.LpddrDevice/dataRateMtps (as-long (get data :dataRateMtps))]))
                   (conj [:db/add id :lpddr_mobile.LpddrDevice/updatedAt (now)]))]
      (-transact port sets)
      (-pull port id))))

(defn delete-lpddr-device
  "Delete a LpddrDevice."
  [port id]
  (-transact port [[:db/retractEntity id]])
  {:id id :deleted true})

;; ── Channel ────────────────────────────────────────────────────────────────
(defn create-channel
  "Create a Channel."
  [port data]
  (require-fields data ["width" "index"])
  (let [id (new-id "lpd_cha")
        e {:db/id id
           :lpddr_mobile.Channel/id id
           :lpddr_mobile.Channel/deviceId (get data :deviceId)
           :lpddr_mobile.Channel/width (as-long (get data :width))
           :lpddr_mobile.Channel/index (as-long (get data :index))
           :lpddr_mobile.Channel/dataRateMtps (as-long (get data :dataRateMtps))
           :lpddr_mobile.Channel/createdAt (now)
           :lpddr_mobile.Channel/updatedAt (now)}]
    (-transact port [e])
    e))

(defn list-channels
  "List Channel with optional filtering + cursor pagination → L4 list map.
   opts: {:filter {<attr-kw> v} :limit N :starting-after <db/id>}."
  ([port] (list-channels port {}))
  ([port opts]
   (let [rows (mapv (fn [e] (-pull port e)) (-find-by-attr port :lpddr_mobile.Channel/id))
         rows (apply-filters rows (:filter opts) [:lpddr_mobile.Channel/deviceId :lpddr_mobile.Channel/width :lpddr_mobile.Channel/index :lpddr_mobile.Channel/dataRateMtps])]
     (paginate rows opts))))

(defn get-channel
  "Retrieve a Channel by id; opts {:expand #{:field}} inlines referenced entities. nil if absent."
  ([port id] (get-channel port id nil))
  ([port id opts]
   (when-let [rec (-pull port id)]
     (let [want (:expand opts)]
       (cond-> rec)))))

(defn update-channel
  "Update a Channel; returns the new entity map, or nil if absent."
  [port id data]
  (when (-pull port id)
    (let [sets (-> []
                   (cond-> (contains? data :deviceId) (conj [:db/add id :lpddr_mobile.Channel/deviceId (get data :deviceId)]))
                   (cond-> (contains? data :width) (conj [:db/add id :lpddr_mobile.Channel/width (as-long (get data :width))]))
                   (cond-> (contains? data :index) (conj [:db/add id :lpddr_mobile.Channel/index (as-long (get data :index))]))
                   (cond-> (contains? data :dataRateMtps) (conj [:db/add id :lpddr_mobile.Channel/dataRateMtps (as-long (get data :dataRateMtps))]))
                   (conj [:db/add id :lpddr_mobile.Channel/updatedAt (now)]))]
      (-transact port sets)
      (-pull port id))))

(defn delete-channel
  "Delete a Channel."
  [port id]
  (-transact port [[:db/retractEntity id]])
  {:id id :deleted true})

;; ── PowerMode ────────────────────────────────────────────────────────────────
(defn create-power-mode
  "Create a PowerMode."
  [port data]
  (require-fields data ["name" "currentMa"])
  (let [id (new-id "lpd_pow")
        e {:db/id id
           :lpddr_mobile.PowerMode/id id
           :lpddr_mobile.PowerMode/deviceId (get data :deviceId)
           :lpddr_mobile.PowerMode/name (get data :name)
           :lpddr_mobile.PowerMode/currentMa (as-double (get data :currentMa))
           :lpddr_mobile.PowerMode/voltageV (as-double (get data :voltageV))
           :lpddr_mobile.PowerMode/createdAt (now)
           :lpddr_mobile.PowerMode/updatedAt (now)}]
    (-transact port [e])
    e))

(defn list-power-modes
  "List PowerMode with optional filtering + cursor pagination → L4 list map.
   opts: {:filter {<attr-kw> v} :limit N :starting-after <db/id>}."
  ([port] (list-power-modes port {}))
  ([port opts]
   (let [rows (mapv (fn [e] (-pull port e)) (-find-by-attr port :lpddr_mobile.PowerMode/id))
         rows (apply-filters rows (:filter opts) [:lpddr_mobile.PowerMode/deviceId :lpddr_mobile.PowerMode/name :lpddr_mobile.PowerMode/currentMa :lpddr_mobile.PowerMode/voltageV])]
     (paginate rows opts))))

(defn get-power-mode
  "Retrieve a PowerMode by id; opts {:expand #{:field}} inlines referenced entities. nil if absent."
  ([port id] (get-power-mode port id nil))
  ([port id opts]
   (when-let [rec (-pull port id)]
     (let [want (:expand opts)]
       (cond-> rec)))))

(defn update-power-mode
  "Update a PowerMode; returns the new entity map, or nil if absent."
  [port id data]
  (when (-pull port id)
    (let [sets (-> []
                   (cond-> (contains? data :deviceId) (conj [:db/add id :lpddr_mobile.PowerMode/deviceId (get data :deviceId)]))
                   (cond-> (contains? data :name) (conj [:db/add id :lpddr_mobile.PowerMode/name (get data :name)]))
                   (cond-> (contains? data :currentMa) (conj [:db/add id :lpddr_mobile.PowerMode/currentMa (as-double (get data :currentMa))]))
                   (cond-> (contains? data :voltageV) (conj [:db/add id :lpddr_mobile.PowerMode/voltageV (as-double (get data :voltageV))]))
                   (conj [:db/add id :lpddr_mobile.PowerMode/updatedAt (now)]))]
      (-transact port sets)
      (-pull port id))))

(defn delete-power-mode
  "Delete a PowerMode."
  [port id]
  (-transact port [[:db/retractEntity id]])
  {:id id :deleted true})

;; ── TimingProfile ────────────────────────────────────────────────────────────────
(defn create-timing-profile
  "Create a TimingProfile."
  [port data]
  (require-fields data ["casLatency" "tRCD"])
  (let [id (new-id "lpd_tim")
        e {:db/id id
           :lpddr_mobile.TimingProfile/id id
           :lpddr_mobile.TimingProfile/deviceId (get data :deviceId)
           :lpddr_mobile.TimingProfile/casLatency (as-long (get data :casLatency))
           :lpddr_mobile.TimingProfile/tRCD (as-long (get data :tRCD))
           :lpddr_mobile.TimingProfile/tRP (as-long (get data :tRP))
           :lpddr_mobile.TimingProfile/createdAt (now)
           :lpddr_mobile.TimingProfile/updatedAt (now)}]
    (-transact port [e])
    e))

(defn list-timing-profiles
  "List TimingProfile with optional filtering + cursor pagination → L4 list map.
   opts: {:filter {<attr-kw> v} :limit N :starting-after <db/id>}."
  ([port] (list-timing-profiles port {}))
  ([port opts]
   (let [rows (mapv (fn [e] (-pull port e)) (-find-by-attr port :lpddr_mobile.TimingProfile/id))
         rows (apply-filters rows (:filter opts) [:lpddr_mobile.TimingProfile/deviceId :lpddr_mobile.TimingProfile/casLatency :lpddr_mobile.TimingProfile/tRCD :lpddr_mobile.TimingProfile/tRP])]
     (paginate rows opts))))

(defn get-timing-profile
  "Retrieve a TimingProfile by id; opts {:expand #{:field}} inlines referenced entities. nil if absent."
  ([port id] (get-timing-profile port id nil))
  ([port id opts]
   (when-let [rec (-pull port id)]
     (let [want (:expand opts)]
       (cond-> rec)))))

(defn update-timing-profile
  "Update a TimingProfile; returns the new entity map, or nil if absent."
  [port id data]
  (when (-pull port id)
    (let [sets (-> []
                   (cond-> (contains? data :deviceId) (conj [:db/add id :lpddr_mobile.TimingProfile/deviceId (get data :deviceId)]))
                   (cond-> (contains? data :casLatency) (conj [:db/add id :lpddr_mobile.TimingProfile/casLatency (as-long (get data :casLatency))]))
                   (cond-> (contains? data :tRCD) (conj [:db/add id :lpddr_mobile.TimingProfile/tRCD (as-long (get data :tRCD))]))
                   (cond-> (contains? data :tRP) (conj [:db/add id :lpddr_mobile.TimingProfile/tRP (as-long (get data :tRP))]))
                   (conj [:db/add id :lpddr_mobile.TimingProfile/updatedAt (now)]))]
      (-transact port sets)
      (-pull port id))))

(defn delete-timing-profile
  "Delete a TimingProfile."
  [port id]
  (-transact port [[:db/retractEntity id]])
  {:id id :deleted true})

;; ── SpeedBin ────────────────────────────────────────────────────────────────
(defn create-speed-bin
  "Create a SpeedBin."
  [port data]
  (require-fields data ["grade" "voltageV"])
  (let [id (new-id "lpd_spe")
        e {:db/id id
           :lpddr_mobile.SpeedBin/id id
           :lpddr_mobile.SpeedBin/deviceId (get data :deviceId)
           :lpddr_mobile.SpeedBin/grade (get data :grade)
           :lpddr_mobile.SpeedBin/voltageV (as-double (get data :voltageV))
           :lpddr_mobile.SpeedBin/dataRateMtps (as-long (get data :dataRateMtps))
           :lpddr_mobile.SpeedBin/createdAt (now)
           :lpddr_mobile.SpeedBin/updatedAt (now)}]
    (-transact port [e])
    e))

(defn list-speed-bins
  "List SpeedBin with optional filtering + cursor pagination → L4 list map.
   opts: {:filter {<attr-kw> v} :limit N :starting-after <db/id>}."
  ([port] (list-speed-bins port {}))
  ([port opts]
   (let [rows (mapv (fn [e] (-pull port e)) (-find-by-attr port :lpddr_mobile.SpeedBin/id))
         rows (apply-filters rows (:filter opts) [:lpddr_mobile.SpeedBin/deviceId :lpddr_mobile.SpeedBin/grade :lpddr_mobile.SpeedBin/voltageV :lpddr_mobile.SpeedBin/dataRateMtps])]
     (paginate rows opts))))

(defn get-speed-bin
  "Retrieve a SpeedBin by id; opts {:expand #{:field}} inlines referenced entities. nil if absent."
  ([port id] (get-speed-bin port id nil))
  ([port id opts]
   (when-let [rec (-pull port id)]
     (let [want (:expand opts)]
       (cond-> rec)))))

(defn update-speed-bin
  "Update a SpeedBin; returns the new entity map, or nil if absent."
  [port id data]
  (when (-pull port id)
    (let [sets (-> []
                   (cond-> (contains? data :deviceId) (conj [:db/add id :lpddr_mobile.SpeedBin/deviceId (get data :deviceId)]))
                   (cond-> (contains? data :grade) (conj [:db/add id :lpddr_mobile.SpeedBin/grade (get data :grade)]))
                   (cond-> (contains? data :voltageV) (conj [:db/add id :lpddr_mobile.SpeedBin/voltageV (as-double (get data :voltageV))]))
                   (cond-> (contains? data :dataRateMtps) (conj [:db/add id :lpddr_mobile.SpeedBin/dataRateMtps (as-long (get data :dataRateMtps))]))
                   (conj [:db/add id :lpddr_mobile.SpeedBin/updatedAt (now)]))]
      (-transact port sets)
      (-pull port id))))

(defn delete-speed-bin
  "Delete a SpeedBin."
  [port id]
  (-transact port [[:db/retractEntity id]])
  {:id id :deleted true})

;; ── JedecSpec ────────────────────────────────────────────────────────────────
(defn create-jedec-spec
  "Create a JedecSpec."
  [port data]
  (require-fields data ["standard" "revision"])
  (let [id (new-id "lpd_jed")
        e {:db/id id
           :lpddr_mobile.JedecSpec/id id
           :lpddr_mobile.JedecSpec/deviceId (get data :deviceId)
           :lpddr_mobile.JedecSpec/standard (get data :standard)
           :lpddr_mobile.JedecSpec/revision (get data :revision)
           :lpddr_mobile.JedecSpec/compliant (as-bool (get data :compliant))
           :lpddr_mobile.JedecSpec/createdAt (now)
           :lpddr_mobile.JedecSpec/updatedAt (now)}]
    (-transact port [e])
    e))

(defn list-jedec-specs
  "List JedecSpec with optional filtering + cursor pagination → L4 list map.
   opts: {:filter {<attr-kw> v} :limit N :starting-after <db/id>}."
  ([port] (list-jedec-specs port {}))
  ([port opts]
   (let [rows (mapv (fn [e] (-pull port e)) (-find-by-attr port :lpddr_mobile.JedecSpec/id))
         rows (apply-filters rows (:filter opts) [:lpddr_mobile.JedecSpec/deviceId :lpddr_mobile.JedecSpec/standard :lpddr_mobile.JedecSpec/revision :lpddr_mobile.JedecSpec/compliant])]
     (paginate rows opts))))

(defn get-jedec-spec
  "Retrieve a JedecSpec by id; opts {:expand #{:field}} inlines referenced entities. nil if absent."
  ([port id] (get-jedec-spec port id nil))
  ([port id opts]
   (when-let [rec (-pull port id)]
     (let [want (:expand opts)]
       (cond-> rec)))))

(defn update-jedec-spec
  "Update a JedecSpec; returns the new entity map, or nil if absent."
  [port id data]
  (when (-pull port id)
    (let [sets (-> []
                   (cond-> (contains? data :deviceId) (conj [:db/add id :lpddr_mobile.JedecSpec/deviceId (get data :deviceId)]))
                   (cond-> (contains? data :standard) (conj [:db/add id :lpddr_mobile.JedecSpec/standard (get data :standard)]))
                   (cond-> (contains? data :revision) (conj [:db/add id :lpddr_mobile.JedecSpec/revision (get data :revision)]))
                   (cond-> (contains? data :compliant) (conj [:db/add id :lpddr_mobile.JedecSpec/compliant (as-bool (get data :compliant))]))
                   (conj [:db/add id :lpddr_mobile.JedecSpec/updatedAt (now)]))]
      (-transact port sets)
      (-pull port id))))

(defn delete-jedec-spec
  "Delete a JedecSpec."
  [port id]
  (-transact port [[:db/retractEntity id]])
  {:id id :deleted true})

;; ── REST surface (host wires these to the kotoba-clj gateway) ──────────────
(def routes
  [{:method "POST" :path "/v1/lpddrdevices" :op :create :entity "LpddrDevice"}
   {:method "GET" :path "/v1/lpddrdevices" :op :list :entity "LpddrDevice"}
   {:method "GET" :path "/v1/lpddrdevices/:id" :op :get :entity "LpddrDevice"}
   {:method "PATCH" :path "/v1/lpddrdevices/:id" :op :update :entity "LpddrDevice"}
   {:method "DELETE" :path "/v1/lpddrdevices/:id" :op :delete :entity "LpddrDevice"}
   {:method "POST" :path "/v1/channels" :op :create :entity "Channel"}
   {:method "GET" :path "/v1/channels" :op :list :entity "Channel"}
   {:method "GET" :path "/v1/channels/:id" :op :get :entity "Channel"}
   {:method "PATCH" :path "/v1/channels/:id" :op :update :entity "Channel"}
   {:method "DELETE" :path "/v1/channels/:id" :op :delete :entity "Channel"}
   {:method "POST" :path "/v1/powermodes" :op :create :entity "PowerMode"}
   {:method "GET" :path "/v1/powermodes" :op :list :entity "PowerMode"}
   {:method "GET" :path "/v1/powermodes/:id" :op :get :entity "PowerMode"}
   {:method "PATCH" :path "/v1/powermodes/:id" :op :update :entity "PowerMode"}
   {:method "DELETE" :path "/v1/powermodes/:id" :op :delete :entity "PowerMode"}
   {:method "POST" :path "/v1/timingprofiles" :op :create :entity "TimingProfile"}
   {:method "GET" :path "/v1/timingprofiles" :op :list :entity "TimingProfile"}
   {:method "GET" :path "/v1/timingprofiles/:id" :op :get :entity "TimingProfile"}
   {:method "PATCH" :path "/v1/timingprofiles/:id" :op :update :entity "TimingProfile"}
   {:method "DELETE" :path "/v1/timingprofiles/:id" :op :delete :entity "TimingProfile"}
   {:method "POST" :path "/v1/speedbins" :op :create :entity "SpeedBin"}
   {:method "GET" :path "/v1/speedbins" :op :list :entity "SpeedBin"}
   {:method "GET" :path "/v1/speedbins/:id" :op :get :entity "SpeedBin"}
   {:method "PATCH" :path "/v1/speedbins/:id" :op :update :entity "SpeedBin"}
   {:method "DELETE" :path "/v1/speedbins/:id" :op :delete :entity "SpeedBin"}
   {:method "POST" :path "/v1/jedecspecs" :op :create :entity "JedecSpec"}
   {:method "GET" :path "/v1/jedecspecs" :op :list :entity "JedecSpec"}
   {:method "GET" :path "/v1/jedecspecs/:id" :op :get :entity "JedecSpec"}
   {:method "PATCH" :path "/v1/jedecspecs/:id" :op :update :entity "JedecSpec"}
   {:method "DELETE" :path "/v1/jedecspecs/:id" :op :delete :entity "JedecSpec"}])

;; collection → CRUD fns, keyed by the /v1/<collection> path segment
(def ^:private handlers
  {"lpddrdevices" {:create create-lpddr-device :list list-lpddr-devices :get get-lpddr-device :update update-lpddr-device :delete delete-lpddr-device}
   "channels" {:create create-channel :list list-channels :get get-channel :update update-channel :delete delete-channel}
   "powermodes" {:create create-power-mode :list list-power-modes :get get-power-mode :update update-power-mode :delete delete-power-mode}
   "timingprofiles" {:create create-timing-profile :list list-timing-profiles :get get-timing-profile :update update-timing-profile :delete delete-timing-profile}
   "speedbins" {:create create-speed-bin :list list-speed-bins :get get-speed-bin :update update-speed-bin :delete delete-speed-bin}
   "jedecspecs" {:create create-jedec-spec :list list-jedec-specs :get get-jedec-spec :update update-jedec-spec :delete delete-jedec-spec}})

(defn- expand-opts [params]
  (when-let [x (:expand params)]
    {:expand (set (map keyword (str/split (str x) #",")))}))

(defn dispatch
  "Route an HTTP-ish request through `routes` to the CRUD fns.
   req: {:method (:get/:post/:patch/:delete) :path /v1/<coll>[/<id>] :params {} :body {}}.
   Returns {:status int :body any} — the runnable L4 service surface."
  [port {:keys [method path params body]}]
  (let [segs (->> (str/split (or path "") #"/") (remove str/blank?) vec)
        coll (get segs 1)
        id   (get segs 2)
        h    (get handlers coll)
        params (or params {})]
    (cond
      (nil? h) {:status 404 :body {:error "unknown collection"}}
      (and (= method :post) (nil? id)) {:status 201 :body ((:create h) port (or body params))}
      (and (= method :get) (nil? id)) {:status 200 :body ((:list h) port params)}
      (and (= method :get) id) (if-let [r ((:get h) port id (expand-opts params))]
                                 {:status 200 :body r} {:status 404 :body {:error "not found"}})
      (and (#{:patch :put} method) id) (if-let [r ((:update h) port id (or body params))]
                                         {:status 200 :body r} {:status 404 :body {:error "not found"}})
      (and (= method :delete) id) {:status 200 :body ((:delete h) port id)}
      :else {:status 405 :body {:error "method not allowed"}})))

(defn healthz []
  {:status "ok" :actor "lpddr_mobile-compat" :tier "L4"
   :lang "clojure" :persistence "datomic-eavt-kotoba"
   :entities entities})
